<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","棣栭〉 -- 浼佷笟寤虹珯",89,158);
$z[2][4]['name']="title";
$z[3]=Array("field","",160,199);
$z[3][4]['name']="writer";
$z[4]=Array("field","",201,240);
$z[4][4]['name']="source";
$z[5]=Array("field","",242,279);
$z[5][4]['name']="body";
$z[6]=Array("field","",281,321);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/dede/templets/xkshop/uploads/allimg/c111212/1323D2554460Z-52312.jpg",323,430);
$z[7][4]['name']="litpic";

?>