{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}棣栭〉 -- 浼佷笟寤虹珯{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dede/templets/xkshop/uploads/allimg/c111212/1323D2554460Z-52312.jpg{/dede:field}
