{dede:noteinfo notename="建站模版" channelid="1" macthtype="string"
refurl="http://www.flxkdns.com" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.flxkdns.com/index.asp?ewebtplcate=0&tp=3&suppertplcate="
startid="1" endid="2" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="right">{/dede:areastart}
    {dede:areaend}<div class="air">		{/dede:areaend}
{/dede:listrule}
