<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
<field:price itemname="市场价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:price>	
<field:trueprice itemname="优惠价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:trueprice>	
	
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:uptime>	
<field:demo_url itemname="演示地址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:demo_url>
<field:top_categroy itemname="模版的顶级分类" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="建站之星,织梦"  maxlength="250" page="">
</field:top_categroy>
<field:second_categroy itemname="模版的二级分类" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="各种行业,电力"  maxlength="250" page="">
</field:second_categroy>
