<?php
$z[0]=Array("global","",1669,1699);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",2131,2161);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",2332,2362);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",2526,2556);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",3376,3406);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("arclist","				\r\n						<div class=\"tem_list_e\">\r\n						<!--tem_list_e_pic-->\r\n						<div class=\"tem_list_e_pic\">\r\n						<a href=\"[field:demo_url /]\" target=\"_blank\"><img src=\"[field:image /]\" alt=\"[field:zn_name /]\" width=\"170\" height=\"170\"></a></div>\r\n						<!--tem_list_e_pic end-->\r\n						<!--tem_list_e_name-->\r\n						<div class=\"tem_list_e_name\">模板编号:[field:code /]</div>\r\n						<!--tem_list_e_name-->\r\n						</div>\r\n					",11119,11635);
$z[5][4]['addfields']="demo_url,code,image,zn_name";
$z[5][4]['row']="8";
$z[5][4]['channelid']="17";

?>