<div class="tem_list_e">
						<!--tem_list_e_pic-->
						<div class="tem_list_e_pic">
						<a href="[field:demo_url /]" target="_blank"><img src="{dede:global.cfg_templeturl /}{field:image /}" alt="[field:zn_name /]" width="170" height="170"></a></div>
						<!--tem_list_e_pic end-->
						<!--tem_list_e_name-->
						<div class="tem_list_e_name">模板编号:[field:code /]</div>
						<!--tem_list_e_name-->
						</div>