<?php
$z[0]=Array("global","",46,76);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",731,761);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",896,926);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",1370,1400);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",1496,1526);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",1591,1621);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",1716,1746);
$z[6][4]['name']="cfg_templeturl";

?>