<?php
$z[0]=Array("arclist","				\r\n						<div class=\"tem_list_e\">\r\n						<!--tem_list_e_pic-->\r\n						<div class=\"tem_list_e_pic\">\r\n						<a href=\"[field:demo_url /]\" target=\"_blank\"><img src=\"[field:image /]\" alt=\"[field:zn_name /]\" width=\"170\" height=\"170\"></a></div>\r\n						<!--tem_list_e_pic end-->\r\n						<!--tem_list_e_name-->\r\n						<div class=\"tem_list_e_name\">模板编号:[field:code /]</div>\r\n						<!--tem_list_e_name-->\r\n						</div>\r\n					",5938,6454);
$z[0][4]['addfields']="demo_url,code,image,zn_name";
$z[0][4]['row']="8";
$z[0][4]['channelid']="17";

?>