<?php
$z[0]=Array("global","",103,133);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",1384,1409);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n<li class=\"\"><a href=\"[field:typeurl/]\"[field:rel/]>[field:typename/]</a></li>\r\n",1429,1653);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>