<?php
$data = array (
  0 => 
  array (
    'cat_id' => '20',
    'cat_name' => '帮助中心',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '8',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统保留',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '21',
    'cat_name' => '新闻中心',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'test',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => 'test',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'test2',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => 'test2',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '14',
    'cat_name' => '虚拟主机',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '15',
    'cat_name' => '网站ICP备案 ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  7 => 
  array (
    'cat_id' => '16',
    'cat_name' => '数据库',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  8 => 
  array (
    'cat_id' => '17',
    'cat_name' => '企业邮局',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  9 => 
  array (
    'cat_id' => '18',
    'cat_name' => '租用托管 ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  10 => 
  array (
    'cat_id' => '19',
    'cat_name' => '如何构建一个自己的网店 ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  11 => 
  array (
    'cat_id' => '22',
    'cat_name' => '域名',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  12 => 
  array (
    'cat_id' => '13',
    'cat_name' => '建站相关',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '如何建立一个站点，这里可以找到答案',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '20',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>